name: Benchmark Update on Main

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    benchmark:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Prepare benchmark metadata
              run: |
                  REPO_URL="https://github.com/${GITHUB_REPOSITORY}"
                  echo "### Benchmark Results" > BENCHMARK.md
                  echo "" >> BENCHMARK.md
                  echo "Executed on: $(date -u +"%Y-%m-%d %H:%M:%S") UTC" >> BENCHMARK.md
                  echo "Commit: [${GITHUB_SHA}](${REPO_URL}/commit/${GITHUB_SHA})" >> BENCHMARK.md
                  echo "" >> BENCHMARK.md

            - name: Run benchmark and append results
              run: pnpm bench | tee -a BENCHMARK.md

            - name: Commit benchmark results
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add BENCHMARK.md
                  git commit -m "Update benchmark results [skip ci]" || echo "No changes to commit"
                  git push
