name: Update Benchmark Results

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - '!src/**/*.test.ts'
            - '!src/**/*.spec.ts'
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: read

jobs:
    update-benchmark:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run benchmark
              uses: NaverPayDev/benchmark-actions@main
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PACKAGE_MANAGER: 'pnpm'
                  TARGET: 'markdown'
                  SOURCE_ROOT: 'src'
